DROP TABLE ACTIVO;
DROP TABLE DEPARTAMENTO;
DROP TABLE DISPO_INTELIIGENTE;
DROP TABLE DISPO_RAM;
DROP TABLE DIVISION;
DROP TABLE EDIFICIO;
DROP TABLE HERRAMIENTA_CONSUMIBLE;
DROP TABLE HISTORICO_ACTIVO_RESPONSABLE;
DROP TABLE HISTORICO_ACTIVO_RESPONSABLE_INTERNO;
DROP TABLE HISTORICO_ACTIVO_USUARIO;
DROP TABLE HISTORICO_HERRAMIENTA_CONSUMIBLE;
DROP TABLE LIBRO;
DROP TABLE MARCA;
DROP TABLE MICROPROCESADOR;
DROP TABLE MODELO;
DROP TABLE PROYECTOR_TV;
DROP TABLE RAM;
DROP TABLE RESPONSABLE_INTERNO;
DROP TABLE RESPONSABLE_RESGUARDO;
DROP TABLE SECTOR;
DROP TABLE SISTEMA_OPERATIVO;
DROP TABLE TIPO_SO;
DROP TABLE TITULO;
DROP TABLE UBICACION;
DROP TABLE USUARIO_FINAL;

--
--TABLES
--

--ACTIVO
CREATE TABLE ACTIVO(
    ACTIVO_ID                   DECIMAL(10, 0)    NOT NULL,
    FACTURA                     VARCHAR(100),
    SERIAL                      VARCHAR(40),
    NUM_INVENTARIO              DECIMAL(10, 0),
    TIPO                        CHAR(1)           NOT NULL,
    NOMBRE                      VARCHAR(40)       NOT NULL,
    ESTADO                      VARCHAR(20)       NOT NULL,
    USUARIO_FINAL_ID            DECIMAL(10, 0)    NOT NULL,
    RESPONSABLE_INTERNO_ID      DECIMAL(10, 0)    NOT NULL,
    RESPONSABLE_RESGUARDO_ID    DECIMAL(10, 0)    NOT NULL,
    MODELO_ID                   DECIMAL(11, 0)    NOT NULL,
    UBICACION_ID                DECIMAL(10, 0)    NOT NULL,
    PRIMARY KEY (ACTIVO_ID)
);

--DEPARTAMENTO
CREATE TABLE DEPARTAMENTO(
    DEPARTAMENTO_ID    DECIMAL(3, 0)    NOT NULL,
    CLAVE              VARCHAR(7),
    NOMBRE             VARCHAR(40)      NOT NULL,
    DIVISION_ID        DECIMAL(2, 0)    NOT NULL,
    PRIMARY KEY (DEPARTAMENTO_ID)
);

--DISPO INTELIGENTE
CREATE TABLE DISPO_INTELIIGENTE(
    ACTIVO_ID               DECIMAL(10, 0)    NOT NULL,
    CARACTERISTICAS         TEXT,
    NUM_PROCESADORES        DECIMAL(2, 0),
    RAM_INSTALADA           DECIMAL(2, 0),
    RAM_MAX                 DECIMAL(2, 0),
    MICROPROCESADOR_ID      DECIMAL(10, 0)    NOT NULL,
    SISTEMA_OPERATIVO_ID    DECIMAL(5, 0)     NOT NULL,
    PRIMARY KEY (ACTIVO_ID)
);

--DISPO_RAM
CREATE TABLE DISPO_RAM(
    DISPO_RAM_ID    DECIMAL(10, 0)    NOT NULL,
    ACTIVO_ID       DECIMAL(10, 0)    NOT NULL,
    RAM_ID          DECIMAL(10, 0)    NOT NULL,
    PRIMARY KEY (DISPO_RAM_ID)
);

--DIVISION
CREATE TABLE DIVISION(
    DIVISION_ID    DECIMAL(2, 0)    NOT NULL,
    ACRONIMO       VARCHAR(10)      NOT NULL,
    NOMBRE         VARCHAR(50)      NOT NULL,
    PRIMARY KEY (DIVISION_ID)
);

--EDIFICIO
CREATE TABLE EDIFICIO(
    EDIFICIO_ID    DECIMAL(5, 0)    NOT NULL,
    NOMBRE         VARCHAR(20)      NOT NULL,
    PRIMARY KEY (EDIFICIO_ID)
);

--HERRAMIENTA_CONSUMIBLE
CREATE TABLE HERRAMIENTA_CONSUMIBLE(
    ACTIVO_ID        DECIMAL(10, 0)    NOT NULL,
    FECHA_COMPRA     DATE              NOT NULL,
    FECHA_CONSUMO    DATE,
    CANTIDAD         DECIMAL(3, 0)     NOT NULL,
    CONTENIDO        VARCHAR(10),
    DESCRIPCION      VARCHAR(500),
    PRIMARY KEY (ACTIVO_ID)
);

--HISTORICO_ACTIVO_RESPONSABLE
CREATE TABLE HISTORICO_ACTIVO_RESPONSABLE(
    HISTORICO_ACTIVO_RESPONSABLE_ID    DECIMAL(10, 0)    NOT NULL,
    FECHA_CAMBIO_RESGUARDO             DATE              NOT NULL,
    RESPONSABLE_RESGUARDO_ID           DECIMAL(10, 0)    NOT NULL,
    ACTIVO_ID                          DECIMAL(10, 0)    NOT NULL,
    PRIMARY KEY (HISTORICO_ACTIVO_RESPONSABLE_ID)
);

--HISTORICO_ACTIVO_RESPONSABLE_INTERNO
CREATE TABLE HISTORICO_ACTIVO_RESPONSABLE_INTERNO(
    HISTORICO_ACTIVO_RESPONSABLE_INT_ID    DECIMAL(10, 0)    NOT NULL,
    FECHA_PRESTAMO                         DATE              NOT NULL,
    RESPONSABLE_INTERNO_ID                 DECIMAL(10, 0)    NOT NULL,
    ACTIVO_ID                              DECIMAL(10, 0)    NOT NULL,
    PRIMARY KEY (HISTORICO_ACTIVO_RESPONSABLE_INT_ID)
);

--HISTORICO_ACTIVO_USUARIO
CREATE TABLE HISTORICO_ACTIVO_USUARIO(
    HISTORICO_ACTIVO_USUARIO_ID    DECIMAL(10, 0)    NOT NULL,
    FECHA_PRESTAMO                 DATE              NOT NULL,
    USUARIO_FINAL_ID               DECIMAL(10, 0)    NOT NULL,
    ACTIVO_ID                      DECIMAL(10, 0)    NOT NULL,
    PRIMARY KEY (HISTORICO_ACTIVO_USUARIO_ID)
);

--HISTORICO_HERRAMIENTA_CONSUMIBLE
CREATE TABLE HISTORICO_HERRAMIENTA_CONSUMIBLE(
    HISTORICO_HERRAMIENTA_CONSUMIBLE_ID    DECIMAL(10, 0)    NOT NULL,
    FECHA_CONSUMO                          DATE              NOT NULL,
    ACTIVO_ID                              DECIMAL(10, 0)    NOT NULL,
    PRIMARY KEY (HISTORICO_HERRAMIENTA_CONSUMIBLE_ID)
);

--LIBRO
CREATE TABLE LIBRO(
    ACTIVO_ID    DECIMAL(10, 0)    NOT NULL,
    EDITORIAL    VARCHAR(40),
    EDICION      VARCHAR(40),
    ANIO         DECIMAL(4, 0),
    AUTOR        VARCHAR(500)      NOT NULL,
    PRIMARY KEY (ACTIVO_ID)
);

--MARCA
CREATE TABLE MARCA(
    MARCA_ID    DECIMAL(5, 0)    NOT NULL,
    NOMBRE      VARCHAR(11)      NOT NULL,
    PRIMARY KEY (MARCA_ID)
);

--MICROPROSESADOR
CREATE TABLE MICROPROCESADOR(
    MICROPROCESADOR_ID    DECIMAL(10, 0)    NOT NULL,
    NOMBRE                VARCHAR(35)       NOT NULL,
    ARQUITECTURA          VARCHAR(10)       NOT NULL,
    GENERACION            VARCHAR(20)       NOT NULL,
    MARCA                 DECIMAL(5, 0)     NOT NULL,
    PRIMARY KEY (MICROPROCESADOR_ID)
);

--MODELO
CREATE TABLE MODELO(
    MODELO_ID    DECIMAL(11, 0)    NOT NULL,
    NOMBRE       VARCHAR(30)       NOT NULL,
    IMAGEN       VARCHAR(100)      NOT NULL,
    MARCA_ID     DECIMAL(5, 0)     NOT NULL,
    PRIMARY KEY (MODELO_ID)
);

--PROYECTOR_TV
CREATE TABLE PROYECTOR_TV(
    ACTIVO_ID         DECIMAL(10, 0)    NOT NULL,
    VGA               DECIMAL(1, 0)     NOT NULL,
    HDMI              DECIMAL(1, 0)     NOT NULL,
    USB               DECIMAL(1, 0)     NOT NULL,
    ETHERNET          DECIMAL(1, 0)     NOT NULL,
    CONTROL_REMOTO    VARCHAR(2)        NOT NULL,
    PRIMARY KEY (ACTIVO_ID)
);

--RAM
CREATE TABLE RAM(
    RAM_ID       DECIMAL(10, 0)    NOT NULL,
    MARCA        VARCHAR(40)       NOT NULL,
    NUM_SERIE    VARCHAR(40)       NOT NULL,
    TIPO         VARCHAR(5)        NOT NULL,
    CAPACIDAD    DECIMAL(3, 0)     NOT NULL,
    PRIMARY KEY (RAM_ID)
);

--RESPONSABLE_INTERNO
CREATE TABLE RESPONSABLE_INTERNO(
    RESPONSABLE_INTERNO_ID    DECIMAL(10, 0)    NOT NULL,
    NOMBRE                    VARCHAR(50)       NOT NULL,
    AP_PATERNO                VARCHAR(50)       NOT NULL,
    AP_MATERNO                VARCHAR(50)       NOT NULL,
    NUM_TRB                   DECIMAL(7, 0)     NOT NULL,
    RFC                       VARCHAR(15)       NOT NULL,
    TELEFONO                  DECIMAL(12, 0)    NOT NULL,
    CORREO                    VARCHAR(70)       NOT NULL,
    DEPARTAMENTO_ID           DECIMAL(3, 0)     NOT NULL,
    TITULO_ID                 DECIMAL(5, 0)     NOT NULL,
    PRIMARY KEY (RESPONSABLE_INTERNO_ID)
);

--RESPONSABLE_RESGUARDO
CREATE TABLE RESPONSABLE_RESGUARDO(
    RESPONSABLE_RESGUARDO_ID    DECIMAL(10, 0)    NOT NULL,
    NOMBRE                      VARCHAR(50)       NOT NULL,
    AP_PATERNO                  VARCHAR(50)       NOT NULL,
    AP_MATERNO                  VARCHAR(50)       NOT NULL,
    NUM_TRB                     DECIMAL(7, 0)     NOT NULL,
    RFC                         VARCHAR(15)       NOT NULL,
    TELEFONO                    DECIMAL(12, 0)    NOT NULL,
    CORREO                      VARCHAR(70)       NOT NULL,
    DEPARTAMENTO_ID             DECIMAL(3, 0)     NOT NULL,
    TITULO_ID                   DECIMAL(5, 0)     NOT NULL,
    PRIMARY KEY (RESPONSABLE_RESGUARDO_ID)
);

--SECTOR
CREATE TABLE SECTOR(
    SECTOR_ID    DECIMAL(5, 0)    NOT NULL,
    NOMBRE       VARCHAR(40)      NOT NULL,
    PRIMARY KEY (SECTOR_ID)
);

--SISTEMA_OPERATIVO
CREATE TABLE SISTEMA_OPERATIVO(
    SISTEMA_OPERATIVO_ID    DECIMAL(5, 0)    NOT NULL,
    VERSION                 VARCHAR(40)      NOT NULL,
    ARQUITECTURA            VARCHAR(15)      NOT NULL,
    TIPO_SO_ID              DECIMAL(6, 0)    NOT NULL,
    PRIMARY KEY (SISTEMA_OPERATIVO_ID)
);

--TIPO
CREATE TABLE TIPO_SO(
    TIPO_SO_ID    DECIMAL(6, 0)    NOT NULL,
    NOMBRE        VARCHAR(40)      NOT NULL,
    PRIMARY KEY (TIPO_SO_ID)
);

--TITULO
CREATE TABLE TITULO(
    TITULO_ID      DECIMAL(5, 0)    NOT NULL,
    NOMBRE         VARCHAR(60)      NOT NULL,
    ABREVIATURA    VARCHAR(10)      NOT NULL,
    PRIMARY KEY (TITULO_ID)
):

--UBICACION
CREATE TABLE UBICACION(
    UBICACION_ID    DECIMAL(10, 0)    NOT NULL,
    PISO            VARCHAR(5),
    NOMBRE          VARCHAR(150)      NOT NULL,
    CUBICULO        VARCHAR(10),
    CORREO          VARCHAR(60),
    TELEFONO        DECIMAL(12, 0),
    EDIFICIO_ID     DECIMAL(5, 0)     NOT NULL,
    PRIMARY KEY (UBICACION_ID)
);

--USUARIO_FINAL
CREATE TABLE USUARIO_FINAL(
    USUARIO_FINAL_ID    DECIMAL(10, 0)    NOT NULL,
    NOMBRE              DECIMAL(5, 0)     NOT NULL,
    SECTOR_ID           DECIMAL(5, 0)     NOT NULL,
    PERFIL              DECIMAL(10, 0)    NOT NULL,
    PRIMARY KEY (USUARIO_FINAL_ID)
);

