-- TARGETA GRAFICA ->DISPO INTELIGENTE Y PROYECTOR
-- TARGETA_GRAFICA SE UNE CON GRAFICA_INTERFAZ_VIDEO
-- INTERFAZ_VIDEO SE UNE CON GRAFICA_INTERFAZ_VIDEO
--FALTA TIPO_TARGETA_GRAFICA SE UNE CON TRAGETA_GRAFICA

--ALGO UNIDAD LECTORA, VER SI HAY TABLA






