ALTER TABLE DICO_DURO DROP FOREIGN KEY FK_DISCO_DURO_TECNOLOGIA_HD;

DROP TABLE IF EXISTS DISCO_DURO;
DROP TABLE IF EXISTS DISPO_DD;
DROP TABLE IF EXISTS TECNOLOGIA_HD;

-- DISCO DURO/ALMACENAMIENTO
CREATE TABLE DISCO_DURO(
    DISCO_DURO_ID           DECIMAL(5,0)    NOT NULL,
    NUMERO_SERIE            VARCHAR(30)     NOT NULL,
    DISCO_DURO_MARCA        VARCHAR(30),
    DISCO_DURO_MODELO       VARCHAR(30),
    DISCO_DURO_CAPACIDAD    DECIMAL(3,0)    NOT NULL,
    TECNOLOGIA_HD_ID        DECIMAL(3,0)    NOT NULL,
    MECANICO_SOLIDO         BIT             NOT NULL,
    PRIMARY KEY (DISCO_DURO_ID)
);

-- DISPOSITIVO_DD
CREATE TABLE DISPO_DD(
    DISPO_DD_ID         DECIMAL(5,0)    NOT NULL,  
    ACTIVO_ID           DECIMAL(10, 0)  NOT NULL,
    DISCO_DURO_ID       DECIMAL(5,0)    NOT NULL,
    PRIMARY KEY (DISPO_DD_ID)
);

-- TECNOLOGIA HD (AQUI VA TECNOLOGIA)
CREATE TABLE TECNOLOGIA_HD(
    TECNOLOGIA_HD_ID    DECIMAL(3,0)    NOT NULL,
    NOMBRE              VARCHAR(30)     NOT NULL,
    PRIMARY KEY (TECNOLOGIA_HD_ID)
);

-- DE DISCO DURO
ALTER TABLE DISCO_DURO ADD CONSTRAINT FK_DISCO_DURO_TECNOLOGIA_HD
    FOREIGN KEY (TECNOLOGIA_HD_ID)
    REFERENCES TECNOLOGIA_HD (TECNOLOGIA_HD_ID);

-- DE DISPO_DD
-- SON DOS ALTER

-- TARGETA GRAFICA ->DISPO INTELIGENTE Y PROYECTOR
-- TARGETA_GRAFICA SE UNE CON GRAFICA_INTERFAZ_VIDEO
-- INTERFAZ_VIDEO SE UNE CON GRAFICA_INTERFAZ_VIDEO
--FALTA TIPO_TARGETA_GRAFICA SE UNE CON TRAGETA_GRAFICA
--FALTAN DISPO PUERTO Y PUERTO, DISPO ESTA CONECTADA A ACTIVO
--ALGO UNIDAD LECTORA, VER SI HAY TABLA
